language: node_js
node_js: node
cache: yarn
deploy:
- provider: npm
  email: opensource@realytics.io
  api_key:
    secure: gu1bAJGF81/ujdeoYi56nLfXI+tWSb4aKpwP9M5GLo10MISWBS7rzvh70IpQTt36QSCM26IBeOE/L7o3h+7tNGLBXgr7qVvaXpQfJPhCJprXCbAOBv8wGMBlg1Cs74Dju9tZavcNiJfDJvb2AeBmqyPfpXNV8WCxWHdP4sFagMZD2zDRWW2T08iKLM/Txp32jZnJzn7ixCcLpBnCI2sMUqGaGhijpHmuXYqhUaXpbGwELLczNktSpwbTJYUZ0KC4uhYEQ7JVhu0e1Rhztzbw1RkkouNtEuCzRNbm4KEi+S8SzTvMD7T5pODpfrNXehOsr0kSTrmRy2LU2cqCdmb84bn74U3p8YOfUPq1Ph5iiWcB1qS1mTD5fCaL4ofi4nOOHGlpRG5EM8JbDNs1yJCcpQ7WqMROyJjtYJYOrTckx3RUTutMmVldJQWP/qo6ArM+eBN++g6mbl+6OWK7RpF4+d2UfyyMsMXbw8J0PTcwc55Nya7PQy/eyRCBYdeSKyWab5fFsXS2vWo3j9BKaUr+BH7v62XwRnGSPFzBWt0jq7QaxvVbuCr74GltORQ/lmbwRyULEFtccGdH0y1jL9E60ML+yISEyo/UkC7s5wK4tRACkVrUk6kmzwAeSHYLaKt2Kg7xZcjIBzsfxCgXtFaMMKJHoswa/t/a2Fu3EXah9lE=
  on:
    tags: true
    repo: Realytics/path-pattern
- provider: pages
  skip_cleanup: true
  github_token:
    secure: BGRw5kfVaPWgXSPn/NEar0SQENv8gvaAaBVwk4fk/h5qwH53GxT+Rp1tjxOT7A+pX84SjO4QRpWrTOm0lTPRPqVIxBNLApoy+QBlWXu+1GIgCCSFAIWxi3Nj5fmDoENIrGevGtEpWIXffVFVEiJFcfWkQMoDQZjIR0bdDjux9NgHOiLwBoL49pc0znjgbVU+74jijHQnhqnbcfGI25VmyQTwihZKeUM3SyNgAEyYroqvtsexbNQqyPZxqTfDGcDtB9m+n5v7G758LqQ6cy5n2yja4HpxNdXIYZfc7ZxPaqKAfR1ZRtfx5jfWCN1mFM3ghQWZTTl1wEpq7oCYA24OIJyiEUHRc764MUpr0awpM/F3GgzvhFMjShVAZwnGx4BLJAhEHAHmG5+kKv77ZY4UCKk7hfS0Qu4P6NpBaeon44WtyVYEDnAzjhsMLEXltD+TjMfqOHGoZvuqu2z3+FO+HV/Cnwiy8bWCwNw44es0tVbUfAwogUU+nXMBB7bgH8cO7lQOA+UkEvg49fzRFTklW7SlbciDOlAmKhKulWBGtJMDxRHx2pUK5fKbIpH535wMwfQ+hSVVU0ZE+KnyGs5xCAd4w7xOCNsXM1q1ztWOs6fY+z/mS0urgendA6Q1zmBMnuIbde07/kpV29krtUnc5zuNKYRNpxc/C2p4WXNlBC0=
  local_dir: "generated-docs"
  on:
    branch: master
